### ISSUE TITLE
获取屏幕的宽高报错

### ISSUE THREAD

**Issue by jancywen** [jancywen/flutter_study#2]
```dart
....
 @override
  Widget build(BuildContext context) {

    // 屏幕适配
    ScreenUtil.init(context, designSize: Size(750, 1334), allowFontScaling: false);

    return MultiProvider(
      providers: providers,
      child: MaterialApp(
....



════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building MyApp(dirty):
MediaQuery.of() called with a context that does not contain a MediaQuery.

No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of(). This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
The context used was: MyApp
    dirty
The relevant error-causing widget was
MyApp                                                                                        package:flutter_study/main.dart:8
When the exception was thrown, this was the stack
#0      MediaQuery.of                                                                 package:flutter/…/widgets/media_query.dart:819
#1      ScreenUtil.init                                                                   package:flutter_screenutil/screenutil.dart:46
#2      MyApp.build                                                                     package:flutter_study/main.dart:42
#3      StatelessElement.build                                                   package:flutter/…/widgets/framework.dart:4701
#4      ComponentElement.performRebuild                             package:flutter/…/widgets/framework.dart:4627
...

```

**Comment by jancywen** [comment]
根据字面意思就是无法冲上下文获取到MediaQuery，**需要在MaterialApp或者WidgetsApp里面使用才可行**。

就是将`ScreenUtil`要放在`MaterialApp`的 `child` 里初始化
